    export const TipoCorEnum = [
        {tipo: "bug",         codigo: "#707e59"},
        {tipo: "dark",        codigo: "#21215a"},
        {tipo: "dragon",      codigo: "#62cad9"},
        {tipo: "electric",    codigo: "#eed277"},
        {tipo: "fairy",       codigo: "#ff7fb2"},
        {tipo: "fighting",    codigo: "#ef6239"},
        {tipo: "fire",        codigo: "#d44f5a"},
        {tipo: "flying",      codigo: "#94b2c7"},
        {tipo: "ghost",       codigo: "#460d6d"},
        {tipo: "grass",       codigo: "#70ca86"},
        {tipo: "ground",      codigo: "#6e491f"},
        {tipo: "ice",         codigo: "#d8f0fa"},
        {tipo: "normal",      codigo: "#fff0c0"},
        {tipo: "poison",      codigo: "rgb(94, 57, 116)"},
        {tipo: "psychic",     codigo: "#cc207c"},
        {tipo: "rock",        codigo: "#8b3e22"},
        {tipo: "steel",       codigo: "#60756e"},
        {tipo: "water",       codigo: "#5d80d1"},
    ]